[package]
name = "camera_driver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiny_http = "0.11.0"
rppal = "0.13.1"
config-file = "0.2.3"
serde = {version = "1.0.137", features = ["derive"]}